### ISSUE TITLE
Music Player doesn't load mp3 data

### ISSUE THREAD

**Issue by ajayns** [ajayns/amoc-project#2]
The music player doesn't seem to play music nor load the mp3 data. The server returns a 'internal error'. The files are served from localhost:8000 which gives all access permissions but some conflict causes the files not to load.

**Comment by TaherPatan** [comment]
Hello..How did you solve the loading of mp3 files? I have downloaded your code and out of curiosity tried to execute it without making any changes..Could you please guide me how you added your own songs in PyMusicMood because in the CSV files I cannot add my own songs..Could you guide me how to do it or link me to some guide? How should I add my own songs according to my mood and add directory to the mp3 files? I am using Windows 10.
